import { useRouter } from "next/router";

import { gql, useQuery } from "@apollo/client";
import Head from "next/head";

import { Header } from "../components/Header";
import { Lesson } from "../components/Lesson";
import { Sidebar } from "../components/Sidebar";
import { Video } from "../components/Video";

const GET_LESSONS_QUERY = gql`
  query {
    lessons {
      id
      slug
      title
      teacher {
        name
        bio
        avatarURL
      }
    }
  }
`;

interface Lesson {
  id: string;
  title: string;
}

export default function Event() {
  const { data } = useQuery<{ lessons: Lesson[] }>(GET_LESSONS_QUERY);

  const router = useRouter();
  const { slug } = router.query;

  return (
    <>
      <Head>
        <title>Event Platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col min-h-screen">
        <Header />

        <main className="flex flex-1">
          {slug ? <Video /> : <div className="flex-1"></div>}

          <Sidebar />
        </main>
      </div>
    </>
  );
}
